### ISSUE TITLE
Minor bug in FtpStream::get

### ISSUE THREAD

**Issue by SamedhG** [dani-garcia/rust_async_ftp#6]
Line 298 in FtpStream in the get function is :
```
self.read_response(status::ABOUT_TO_SEND).await?;
```
but should be 
```
self.read_response_in(&[status::ABOUT_TO_SEND, status::ALREADY_OPEN]).await?;
```
(same as in the `FtpStream::retr` function)

Can this be fixed in the next release?

**Comment by dani-garcia** [comment]
Sounds reasonable, can you make a PR changing it?

**Comment by SamedhG** [comment]
Yeah will do.

**Comment by SamedhG** [comment]
Thanks! How often do updates get pushed to crates?

**Comment by dani-garcia** [comment]
Usually as soon as there are some changes, 4.0.3 is up now with your PR included.

**Comment by SamedhG** [comment]
Thank you so much! This was very helpful
